Read EMAC from EEPROM on uz3eg-iocc
foundriesio/meta-lmp pull request #300
Opened 2021-03-31 08:00 UTC by AriParkkila

Remove fixed EMAC address from device-tree and read it from EEPROM.

Tested on an AES-ZU3EG-1-SK-G evaluation board.

Without this change:
```
Warning: ethernet@ff0e0000 using MAC address from DT
ZynqMP> printenv ethaddr
ethaddr=00:0a:35:00:02:90
```
With this change and EEPROM UNinitialized:
```
Warning: ethernet@ff0e0000 (eth0) using random MAC address - c2:d0:ec:05:1d:af
```
Write MAC on EEPROM:
```
Hit any key to stop autoboot:  0
ZynqMP> i2c dev 2
Setting bus to 2
ZynqMP> mm.b 0
00000000: 60 ? 12
00000001: 09 ? 34
00000002: 00 ? 56
00000003: 20 ? 78
00000004: 00 ? 9a
00000005: 00 ? bc
00000006: 00 ? q
ZynqMP> i2c write 0 51 20 6
ZynqMP> reset
...
Warning: ethernet@ff0e0000 using MAC address from ROM
```

2021-04-05 22:24 UTC, ricardosalveti commented on meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/device-tree/device-tree/uz3eg-iocc/system-board.dtsi
> +        chosen {
Can you replace space with tab in this block? The rest of the file is using tab instead of spaces.

2021-04-05 22:26 UTC, ricardosalveti requested changes
On minor comment, but works as expected.

Can you just add your git sign off to the git commit? 'git commit -s --amend' and a force push will do the work.

Thanks!

2021-04-08 11:09 UTC, esajaa commented
Signed-off-by: Esa Jaaskela <esa.jaaskela@pelion.com>

2021-04-08 23:24 UTC, ricardosalveti commented
Thanks, pushed manually as https://github.com/foundriesio/meta-lmp/commit/b65a7a606d6b51da0714fc30a2a3e58bbd2c8cd6.

2021-04-08 23:24 UTC, closed without merging